cal/urls.py
from django.conf.urls import patterns, url
from cal.views import EventList, EventDetail, EntryUpdate, EntryCreate, EntryDelete, MonthArchive, EventCreateView, EventUpdateView, Archive

urlpatterns = patterns('',
    url(r'^list$', EventList.as_view(), name='index'),
    url(r'^event/(?P<pk>\d+)/$', EventDetail.as_view(), name='detail'),
    url(r'^entry/(?P<pk>\d+)/switch_to/(?P<to_id>\d+)/$', EntryUpdate.as_view(), name='entry_update'),
    url(r'^entry/add/(?P<to_id>\d+)/$', EntryCreate.as_view(), name='entry_add'),
    url(r'^entry/delete/(?P<pk>\d+)/$', EntryDelete.as_view(), name='entry_delete'),
    url(r'^archive/$', Archive.as_view(), name='archive'),
    url(r'^archieve/(?P<year>\d{4})/(?P<month>\d+)/$',
        MonthArchive.as_view(month_format='%m'),
        name="archive_month"),
    url(r'^event/add/$', EventCreateView.as_view(), name='event_add'),
    url(r'^event/(?P<pk>\d+)/edit$', EventUpdateView.as_view(), name='event_edit'),
)

kalendarz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
import permission; permission.autodiscover()
from galeria.views import HomeView


urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'kalendarz.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^cal/', include('cal.urls')),
	url(r'^gallery/', include('galeria.urls')),
	(r'^accounts/', include('allauth.urls')),
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^profile/', include('playerprofile.urls')),
	url(r'^streams/$', TemplateView.as_view(template_name='int_tv.html'), name='streams'),
	url(r'^youtube/$', TemplateView.as_view(template_name='int_yt.html'), name='youtube'),
	url(r'^squadxml/$', TemplateView.as_view(template_name='squad.xml', content_type='text/xml'), name='squadxml'),
	url(r'^servers/$', TemplateView.as_view(template_name='servers.html'), name='servers'),

)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models.signals import post_save
from django.dispatch import receiver

#domyslny czas rozpoczecia eventu
def default_start_time():
    now = datetime.now()
    start = now.replace(hour=20, minute=0, second=0, microsecond=0)
    return start + timedelta(days=1)  

LIST_CLASSES = [
	('list-group-item-warning', 'warning'),
	('list-group-item-info', 'info'),
	('list-group-item-success', 'success'),
	('list-group-item-danger', 'danger'),
	('list-group-item-default', 'default'),
]

# Create your models here.

class EventType(models.Model):
	name = models.CharField(max_length=100, verbose_name='nazwa')
	css_class = models.CharField(max_length=50, verbose_name='klasa css', blank=True, 
		choices=LIST_CLASSES,
		default='')
	
	class Meta:
		verbose_name = 'typ wydarzenia'
		verbose_name_plural = 'Typy wydarzeń'

	def __str__(self):
		return self.name


class Terrain(models.Model):
	name = models.CharField(max_length=50, verbose_name='nazwa')
	pic = models.ImageField(upload_to='terrains', blank=True, null=True)
	is_active = models.BooleanField(default=True, verbose_name='aktywna')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'mapa'
		verbose_name_plural = 'mapy'

class Event(models.Model):
	title = models.CharField(max_length=200, verbose_name='tytuł')
	author = models.CharField(max_length=200, verbose_name='autor')
	datetime = models.DateTimeField(default=default_start_time, verbose_name='data i czas')
	type = models.ForeignKey(EventType, verbose_name='typ')
	#details = models.TextField(max_length=5000, blank=True, verbose_name='szczegóły')
	url = models.URLField(blank=True, verbose_name='Link')
	terrain = models.ForeignKey(Terrain, null=True, blank=True, verbose_name='Mapa')
	is_open = models.BooleanField(default=True, verbose_name='otwarte')
	created_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
		verbose_name='stworzone przez', null=False,blank=False, editable=False)

	class Meta:
		verbose_name = 'wydarzenie'
		verbose_name_plural = 'wydarzenia'
		ordering = ['datetime']

	def __str__(self):
		return self.title

	def is_mission(self):
		return self.type.name=='Misja'

	def is_course(self):
		return self.type.name=='Szkolenie'

	def is_training(self):
		return self.type.name=='Trening'

	def is_campaign(self):
		return self.type.name=='Kampania'

	def date(self):
		return self.datetime.date()
	date.short_description = "data"

	def time(self):
		return self.datetime.time()
	time.short_description = "godzina"

	def slots_no(self):
		return self.slot_set.count()
	slots_no.short_description = "liczba slotów"

	def slots_taken(self):
		count = 0
		for slot in self.slot_set.all():
			if slot.is_taken():
				count+=1
		return count

	def has_open_slots(self):
		for slot in self.slot_set.all():
			if not slot.is_taken():
				return True
		return False

	def get_absolute_url(self):
		return reverse_lazy('detail', kwargs={'pk':self.pk})






class SlotType(models.Model):
	name = models.CharField(max_length=100, verbose_name='nazwa')
	translation = models.CharField(max_length=100, blank=True, null=False, default='', verbose_name='Tłumaczenie')
	description = models.TextField(max_length=5000, blank=True, verbose_name='Opis')
	
	class Meta:
		verbose_name = 'typ slotu'
		verbose_name_plural = 'typy slotów'
		ordering = ['pk']

	def __str__(self):
		return self.name




class Slot(models.Model):
	group_name = models.CharField(max_length=50, blank = True, verbose_name='nazwa grupy')
	type = models.ForeignKey(SlotType, verbose_name='typ')
	event = models.ForeignKey(Event, verbose_name='wydarzenie')
	order = models.IntegerField(default=0, max_length=20, verbose_name='kolejność')

	class Meta:
		verbose_name = 'slot'
		verbose_name_plural = 'sloty' 

	def __str__(self):
		return "[{0}] {1}".format(str(self.pk), self.type.name)

	def is_taken(self):
		try:
			return self.entry!=None
		except ObjectDoesNotExist:
			return False
	is_taken.boolean=True

	def event_datetime(self):
		return self.event.datetime
	event_datetime.short_description = "data i czas wydarzenia"

	#def reserved_by(self):
	#	return self.archive_set.first().user




class Entry(models.Model):
	slot = models.OneToOneField(Slot)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, verbose_name='użytkownik')
	absence = models.BooleanField(default=False, verbose_name='nieobecność')
	
	class Meta:
		verbose_name = 'zapis'
		verbose_name_plural = 'zapisy'

	def __str__(self):
		return "{0} | {1} - {2}".format(self.slot.event.title, self.user, self.slot)

	def mission(self):
		return self.slot.event.title
	mission.short_description = "Wydarzenie"

	def get_absolute_url(self):
		return reverse('detail', kwargs={'pk': self.slot.event.pk})



from permission import add_permission_logic
from permission.logics import AuthorPermissionLogic, GroupInPermissionLogic
add_permission_logic(Event, AuthorPermissionLogic(
	field_name='created_by',
	change_permission=True,
	delete_permission=False,
))
add_permission_logic(Event, GroupInPermissionLogic(
	group_names=['Administratorzy', 'Moderator'],
	any_permission=True,
	))
add_permission_logic(Event, GroupInPermissionLogic(
	group_names=['Member'],
	add_permission=False,
	change_permission=False,
	delete_permission=False,
	))
add_permission_logic(Entry, GroupInPermissionLogic(
	group_names=['Member'],
	add_permission=True,
	change_permission=False,
	delete_permission=False,
	))





######SIGNALS#########
# @receiver(post_save, sender=event)

cal/forms.py
from django import forms
from cal.models import Entry, Event, Slot
from extra_views import InlineFormSet


class EntryForm(forms.ModelForm):
	#user = forms.ModelChoiceField()

	class Meta:
		model = Entry
		exclude = []
		widgets = {
			'slot': forms.HiddenInput(),
			'user': forms.HiddenInput(),
			'absence': forms.HiddenInput(),
		}


class SlotInline(InlineFormSet):
	model=Slot
	exclude = []
	extra=20
	max_num=25

class EventForm(forms.ModelForm):
	class Meta(object):
		exclude =[]
		model = Event
		

cal/views.py
from braces.views import LoginRequiredMixin, GroupRequiredMixin
from cal.forms import EntryForm, SlotInline, EventForm
from cal.models import Event, Slot, Entry
from datetime import datetime, timedelta
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Count
from django.forms import HiddenInput
from django.forms.formsets import all_valid
from django.forms.models import modelform_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, FormView, TemplateView, RedirectView
from django.views.generic.dates import MonthArchiveView
from extra_views import CreateWithInlinesView, UpdateWithInlinesView
from permission.decorators import permission_required
#mixins:

class AuthorRequiredMixin(object):
	def dispatch(self, request, *args, **kwargs):
		obj = self.get_object()
		result = super(AuthorRequiredMixin, self).dispatch(request, *args, **kwargs)
		if self.object.user != self.request.user:
			return redirect(obj)
		return result

class EventAuthorRequiredMixin(object):
	def dispatch(self, request, *args, **kwargs):
		obj = self.get_object()
		result = super(EventAuthorRequiredMixin, self).dispatch(request, *args, **kwargs)
		if self.object.created_by != self.request.user:
			return redirect(obj)
		return result

class EventGroupRequiredMixin(object):
	def dispatch(self, request, *args, **kwargs):
		result = super(EventGroupRequiredMixin, self).dispatch(request, *args, **kwargs)
		if self.request.user.groups.filter(name='Member').exists() or self.request.user.groups.filter(name='Admin').exists():
			return result
		return reverse_lazy('index')


# Create your views here.


class EventList(ListView):
	queryset= Event.objects.order_by('datetime').filter(is_open=True)




class EventDetail(LoginRequiredMixin, DetailView):
	model = Event

	def is_member(self):
		return self.request.user.groups.filter(name='Member').exists()

	def loggedin_user_entry(self):
		for slot in self.object.slot_set.all():
			try:
				slot_user = slot.entry.user
			except ObjectDoesNotExist:
				slot_user = None
			if slot_user == self.request.user:
				return slot.entry
		return False


	def is_signed_up(self):
		for slot in self.object.slot_set.all():
			try:
				slot_user = slot.entry.user
			except ObjectDoesNotExist:
				slot_user = None
			if slot_user == self.request.user:
				return True
		return False

	def can_quit(self):
		if self.is_member() and (timezone.now() + timedelta(days=1) < self.object.datetime):
			return True
		return False

	def can_switch(self):
		if self.is_member() and (timezone.now() + timedelta(seconds = 600) <= self.object.datetime):
			return True
		return False

	def is_logged_in(self, slot_usr):
		if slot_usr == self.request.user:
			return True
		return False

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(EventDetail, self).get_context_data(**kwargs)
		context['slot_list'] = self.object.slot_set.order_by('group_name', 'order', 'type')
		context['is_signed_up'] = self.is_signed_up()
		context['loggedin_user_entry'] = self.loggedin_user_entry()
		context['can_quit'] = self.can_quit()
		context['can_switch'] = self.can_switch()
		context['is_member'] = self.is_member()
		try:
			context['terrain_pic'] = self.object.terrain.pic.url
		except:
			pass
		return context




class EntryUpdate(AuthorRequiredMixin, UpdateView):
	model = Entry
	exclude = []
	form_class =  EntryForm

	def dispatch(self, request, *args, **kwargs):
		#dostep tylko dla zapisanego usera
		obj = self.get_object()
		if obj.user != self.request.user:
			return redirect(obj)
		return super(EntryUpdate, self).dispatch(request, *args, **kwargs)

	def get_initial(self):
		to_id = self.kwargs['to_id']
		self.initial.update({'user': self.request.user, 
							'slot': Slot.objects.get(pk=to_id)})
		return super(EntryUpdate, self).get_initial()

	def get_context_data(self, **kwargs):
		context = super(EntryUpdate, self).get_context_data(**kwargs)
		context['nowy_slot'] = Slot.objects.get(pk=self.kwargs['to_id'])
		return context


class EntryDelete(AuthorRequiredMixin, DeleteView):
	model = Entry
	#success_url = reverse_lazy('index', )

	def get_success_url(self):
		return reverse('detail', kwargs={'pk': self.object.slot.event.pk})



@permission_required('cal.add_entry', raise_exception=True)
class EntryCreate(LoginRequiredMixin, FormView):
	template_name= 'cal/entry_create.html'
	form_class = EntryForm

	def get_initial(self):
		to_id = self.kwargs['to_id']
		self.initial.update({'user': self.request.user, 
							'slot': Slot.objects.get(pk=to_id)})
		return super(EntryCreate, self).get_initial()

	def get_context_data(self, **kwargs):
		context = super(EntryCreate, self).get_context_data(**kwargs)
		context['slot'] = Slot.objects.get(pk=self.kwargs['to_id'])
		return context

	def form_valid(self, form):
		form.save()
		return redirect('detail', pk=Slot.objects.get(pk=self.kwargs['to_id']).event.pk)

	success_url = reverse_lazy('detail', )




def home(request):
	return render(request, 'home.html')








####ZOSTAWIC NA POZNIEJ DO ZROBIENIA WIDOKU KALENDARZA
class MonthArchive(MonthArchiveView):
	queryset = Event.objects.all()
	date_field = 'datetime'
	make_object_list = True
	allow_future = True
####ZOSTAWIC NA POZNIEJ DO ZROBIENIA WIDOKU KALENDARZA





#@permission_required('cal.add_event', raise_exception=True)
class EventCreateView(GroupRequiredMixin, CreateWithInlinesView):
	group_required = u'Member'
	raise_exception = True
	model = Event
	slug_field = 'event_id'
	class Meta:
		exclude = []
	inlines = [SlotInline]



	def forms_valid(self, form, inlines):
		form.instance.created_by = self.request.user
		return super(EventCreateView, self).forms_valid(form, inlines)

	
	# def get_success_url(self):
	# 	return self.object.get_absolute_url()

####trzeba sprobowac z samym initial, wrzucic form.created_by,
####dodac czas utworzenia



@permission_required('cal.change_event', raise_exception=True)
class EventUpdateView(UpdateWithInlinesView):
	model = Event
	form_class = EventForm
	class Meta:
		exclude = []
	inlines = [SlotInline]


	def get_success_url(self):
		return self.object.get_absolute_url()



class Archive(RedirectView):
	#url = reverse('archive_month')
	# pattern_name = 'archive_month'
	def get_redirect_url(self, *args, **kwargs):
		year = datetime.now().strftime('%Y')
		month = datetime.now().strftime('%m')
		return reverse_lazy('archive_month', kwargs={'year':year, 'month':month})

kalendarz/templates/cal/entry_confirm_delete.html
{% extends "base.html" %}
{% block title %}Potwierdź wypis{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
	<table class="table table-bordered">
		<tr>
			<td>
				{{ object.slot.event|upper }}
			</td>
			<td>
				{{ object.slot.event.date }} {{ object.slot.event.time }}
			</td>
		</tr>
		<tr>
			<td>
				{{ object.slot.group_name|upper }}
			</td>
			<td>
				{{ object.slot.type|upper }}
			</td>
		</tr>
		{% if request.user.is_staff %}
		<tr>
			<td>
				ID: {{ object.pk }}
			</td>
			<td>
				Użytkownik: {{ object.user }}				
			</td>
		</tr>
		{% endif %}
	</table>
    <p>Czy na pewno chcesz wypisać się z misji? </p>
    <input class="btn btn-primary" type="submit" value="Wypisz" />
</form>

{% endblock %}

kalendarz/templates/cal/entry_create.html
{% extends "base.html" %}
{% block title %}Zapis na misje{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <table class="table table-bordered">
    	{{ form }}
		{{ form.errors }}
		<tr>
			<td>
				{{ slot.event|upper }}
			</td>
			<td>
				{{ slot.event.date }} {{ slot.event.time }}
			</td>
		</tr>
		<tr>
			<td>
				{{ slot.group_name|upper }}
			</td>
			<td>
				{{ slot.type|upper }}
			</td>
		</tr>
    </table>
    <input class="btn btn-primary" type="submit" value="Zapisz się" />
</form>

{% endblock %}

kalendarz/templates/cal/entry_form.html
{% extends "base.html" %}
{% block title %}Zmiana slotu{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
{{ form }}
	{{form.errors}}
	<table class="table table-bordered">
		<tr>
			<td>
				{{ object.slot.event|upper }}
			</td>
			<td>
				{{ object.slot.event.date }} {{ object.slot.event.time }}
			</td>

		</tr>
		<tr>
			<td>
				Obecny Slot:
			</td>
			<td>
				{{ object.slot.group_name|upper }}
			</td>
			<td>
				{{ object.slot.type|upper }}
			</td>
		</tr>
		<tr>
			<td>
				<strong>Nowy Slot:</strong>
			</td>
			<td>
				{{ nowy_slot.group_name|upper }}
			</td>
			<td>
				{{ nowy_slot.type|upper }}
			</td>
		</tr>

				


	</table>
	<input class="btn btn-primary" type="submit" value="Zmień slot" />
</form>

{% endblock %}

kalendarz/templates/cal/event_archive_month.html
{% extends "base.html" %}
{% block title %}Archiwum{% endblock %}


{% block content %}

{% regroup object_list by date as event_list %}

{% if event_list %}
	{% for event in event_list %}
	<div class="panel panel-default">
		<div class="panel-heading">{{ event.grouper }}</div>
		<ul class="list-group">
			{% for item in event.list %}
			<a href="{% url 'detail' item.pk %}">
				<li class="list-group-item 
					{{ item.type.css_class }}">
				
				<span class="pull-left col-md-1">{{item.time|time:"H:i"}}</span>
				<strong class="text-uppercase">
					{{ item.title }} 
				</strong>
				<span class="pull-right badge">{{ item.slots_taken }}/{{ item.slots_no }}</span>
				</li></a>
			{% endfor %}
		</ul>

	</div>

	{% endfor %}

{% else %}
<h2 class="">Brak wydarzeń do wyświetlenia</h2>

{% endif %}


<nav>
  	<ul class="pager">
	  	{% if previous_month %}
	    	<li class="previous"><a href="{% url 'archive_month' year=previous_month|date:'Y' month=previous_month|date:'m' %}"><span aria-hidden="true">&larr;</span> {{ previous_month|date:"F Y" }}</a></li>
	  	{% endif %}
      	{% if next_month %}
	    	<li class="next"><a href="{% url 'archive_month' year=next_month|date:'Y' month=next_month|date:'m' %}">{{ next_month|date:"F Y" }} <span aria-hidden="true">&rarr;</span></a></li>
		{% endif %}

  </ul>
</nav>


{% endblock %}

kalendarz/templates/cal/event_detail.html
{% extends "base.html" %}
{% block title %}{{ object.title }} - {{object.type}}{% endblock %}

{% load cal_tags %}

{% block content %}
{# <div class="col-md-1"></div>#}
<div class="container col-md-12" {# style="background-color: #272B30; border-radius: 15px;" #}>
    <div style="margin-top: 20px;" class="panel {% if not event.is_open %}panel-danger{% else %}panel-default{% endif%}">
        <div class="panel-heading">
          <h4 class="panel-title">
              Szczegóły
          </h4>
                
        </div>
        <table class="table table-bordered">
          {% if not event.is_open %}
          <caption><h4 class="text-danger">Wydarzenie zakończone</h4></caption>
          {% endif %}
          <tr>
          	<td class="col-md-2">Tytuł</td>
          	<td>{{ event|upper }}</td>
          </tr>
          <tr>
            <td>Data</td>
            <td>{{event.date}}</td>
          </tr>
          <tr>
            <td>Godzina</td>
            <td>{{event.time|time:"H:i"}}</td>
          </tr>
          <tr>
            <td>Sloty</td>
            <td>{{event.slots_taken}}/{{event.slots_no}}</td>
          </tr>
          <tr>
            <td>Autor</td>
            <td>{{event.author}}</td>
          </tr>
          <tr>
            <td>Mapa</td>
            <td>{{ event.terrain }}</td>
          </tr>
          <tr>
            <td>Typ</td>
            <td>{{event.type}}</td>
          </tr>
          <tr>
          	<td>OPORD</td>
          	<td>
              {% if event.url %}
              <a href="{{event.url}}">{{ event.url }}</a>
              {% else %}
              Brak
              {% endif %}
            </td>
          </tr>
        </table>
        </div>




    <!-- panel od slotow-->
    <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
                Sloty
            </h4>
            
          </div>
          
          {% if slot_list %}
            <table class="table table-hover">
            {% for slot in slot_list %}
              {% compare_users slot.entry.user request.user as is_logged_in_user %}
              <tr class="
              {% if event.is_open %}
                  {% if is_logged_in_user %}success
                  {% elif slot.entry %}info
                  {% else %}
                  {% endif %}
              {% else %}
                  {% if is_logged_in_user %}success
                  {% elif not slot.entry %}active
                  {% elif slot.entry.absence %}warning
                  {% else %}info
                  {% endif %}
              {% endif %}">
                <td class="col-lg-2 text-right">
                  <small>{{ slot.group_name }}</small>
                </td>
                <td>
                  <a tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="{{ slot.type.translation }}" data-content="{{ slot.type.description }}">
                  {{ slot.type }}
                  </a>
                </td>
                <td>{% if slot.entry %}{{ slot.entry.user }}
                        {% if is_logged_in_user and can_quit%}
                        <a href="{% url 'entry_delete' slot.entry.pk %}">[Wypisz się]
                        {% endif %}
                  {% else %}
                    <small>
                      <em>Pusty</em>
                        {% if is_signed_up and can_switch %}
                          <a href="{% url 'entry_update' pk=loggedin_user_entry.pk to_id=slot.pk %}">[Przepisz się]</a>
                        {% elif event.is_open and not is_signed_up and is_member %}
                          <a href="{% url 'entry_add' slot.pk %}">[Zapisz się]</a>
                        {% endif %}
                      
                    </small>
                  {% endif %}
                </td>
                {% if not event.is_open %}
                <td class="text-right">
                  {% if not slot.entry and not slot.entry.absence %}
                    
                  {% elif not slot.entry.absence %}
                    <span class="glyphicon glyphicon-ok-circle"></span>
                  {% else %}
                    <span class="glyphicon glyphicon-ban-circle"></span>
                  {% endif %}
                </td>
                {% endif %}
              </tr>
              
              {% endfor %}
            </table>
            
          {% else %}
            <div class="panel-body">Brak slotów</div>
          {% endif %}
    </div>

    {% if user has 'cal.change_event' of object %}
      <div>
        <a href="{% url 'event_edit' event.pk %}" class="btn btn-default">Edytuj</a>
      </div>
    {% endif %}
</div>
<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

{% endblock %}



{% if event.terrain %}
  {% if event.terrain.pic.url %}

        <style>
        body { 
       background: -webkit-linear-gradient(-90deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 25%, rgba(255,255,255,1) 75%, rgba(255,255,255,1) 100%), url("{{ terrain_pic }}");
      background: -moz-linear-gradient(180deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 25%, rgba(255,255,255,1) 75%, rgba(255,255,255,1) 100%), url("{{ terrain_pic }}");
      background: linear-gradient(180deg, rgba(255,255,255,0) 0, rgba(255,255,255,0) 25%, rgba(255,255,255,1) 75%, rgba(255,255,255,1) 100%), url("{{ terrain_pic }}");
      background-repeat: no-repeat;
      background-position: 50% 100%, center top;
      -webkit-background-origin: padding-box;
      background-origin: padding-box;
      -webkit-background-clip: border-box;
      background-clip: border-box;
      -webkit-background-size: cover;
      background-size: cover;
      background-attachment: fixed;
          }
        </style>
 
    {% block style %}
    {% endblock %}
  {% endif %}
{% endif %}









{# 
<div>
  <table class="table table-bordered">
    <tr>
      <td class="col-md-1">is signed:</td>
      <td>{{ is_signed_up }}</td>
    </tr>
    <tr>
      <td>can_quit</td>
      <td>{{ can_quit }}</td>
    </tr>
    <tr>
      <td>can_switch</td>
      <td>{{ can_switch }}</td>
    </tr>
    <tr>
      <td>is_member:</td>
      <td>{{ is_member }}</td>
    </tr>
  </table>
</div>







 #}

kalendarz/templates/cal/event_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	<div class='col-md-5'>
		{% bootstrap_form form %}
		<input class="btn btn-primary" type="submit" value="Wyślij" />
	</div>
	<div class='col-md-7'>
	{% for formset in inlines %}
		<div class="panel panel-primary">
		<div class="panel-heading">
			<h4 class="panel-title">Sloty</h4>
		</div>
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th>
							Nazwa Grupy
						</th>
						<th>
							Typ slotu
						</th>
						<th>
							Kolejność
						</th>
					</tr>
				</thead>
				<tbody>
				{% for form in formset %}	
						<tr class="form-container form-group form-group-sm">
							{{form.id}}
							{{ form.hidden_fields.as_hidden }}

								<td>	
									{% bootstrap_field form.group_name layout='inline'%}
								</td>
								<td>
									{% bootstrap_field form.type layout='inline' %}
								</td>
								<td class="col-md-2">
									{% bootstrap_field form.order layout='inline' %}
								</td>
								{% if form.instance.pk and formset.can_delete %}
								<td>
									{% bootstrap_field form.DELETE layout='inline' %}
								</td>
								{% endif %}
						</tr>
					</tbody>
				{% endfor %}
	    	</table>
	    </div>
	    {{ formset.management_form }}
	{% endfor %}
	</div>
</form>



{% endblock %}




{% block script %}
<link rel="stylesheet" type="text/css" href="{% static '/static/css/jquery.datetimepicker.css' %}"/ >
<script src="{% static '/static/js/jquery.js' %}"></script>
<script src="{% static '/static/js/jquery.datetimepicker.js' %}"></script>
<script>jQuery('#id_datetime').datetimepicker({
 lang:'pl',
 format:'d.m.Y H:i',
 defaultTime:'20:00',
 dayOfWeekStart: 1,});</script>
{% endblock %}

kalendarz/templates/cal/event_list.html
{% extends "base.html" %}
{% block title %}Nadchodzące wydarzenia{% endblock %}

{% block style %}
{% endblock %}

{% block content %}

{% regroup object_list by date as event_list %}

{% if event_list %}
	{% for event in event_list %}
	<div class="panel panel-default">
		<div class="panel-heading">{{ event.grouper }}</div>
		<ul class="list-group">
			{% for item in event.list %}
			<a href="{% url 'detail' item.pk %}">
				<li class="list-group-item 
					{{ item.type.css_class }}">
				
				<span class="pull-left col-md-1">{{item.time|time:"H:i"}}</span>
				<strong class="text-uppercase">
					{{item.type}}: {{ item.title }}
				</strong>
				<span class="pull-right badge">{{ item.slots_taken }}/{{ item.slots_no }}</span>
				</li></a>
			{% endfor %}
		</ul>

	</div>

	{% endfor %}

{% else %}
<h2 class="">Brak wydarzeń do wyświetlenia</h2>

{% endif %}



{% endblock %}