cal/urls.py
from django.conf.urls import patterns, url
from cal.views import EventList, EventDetail, EntryUpdate, EntryCreate, EntryDelete, MonthArchive, EventCreateView, EventUpdateView, Archive

urlpatterns = patterns('',
    url(r'^list$', EventList.as_view(), name='index'),
    url(r'^event/(?P<pk>\d+)/$', EventDetail.as_view(), name='detail'),
    url(r'^entry/(?P<pk>\d+)/switch_to/(?P<to_id>\d+)/$', EntryUpdate.as_view(), name='entry_update'),
    url(r'^entry/add/(?P<to_id>\d+)/$', EntryCreate.as_view(), name='entry_add'),
    url(r'^entry/delete/(?P<pk>\d+)/$', EntryDelete.as_view(), name='entry_delete'),
    url(r'^archive/$', Archive.as_view(), name='archive'),
    url(r'^archieve/(?P<year>\d{4})/(?P<month>\d+)/$',
        MonthArchive.as_view(month_format='%m'),
        name="archive_month"),
    url(r'^event/add/$', EventCreateView.as_view(), name='event_add'),
    url(r'^event/(?P<pk>\d+)/edit$', EventUpdateView.as_view(), name='event_edit'),
)

kalendarz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
import permission; permission.autodiscover()
from galeria.views import HomeView


urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'kalendarz.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^cal/', include('cal.urls')),
	url(r'^gallery/', include('galeria.urls')),
	(r'^accounts/', include('allauth.urls')),
	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^profile/', include('playerprofile.urls')),
	url(r'^streams/$', TemplateView.as_view(template_name='int_tv.html'), name='streams'),
	url(r'^youtube/$', TemplateView.as_view(template_name='int_yt.html'), name='youtube'),
	url(r'^squadxml/$', TemplateView.as_view(template_name='squad.xml', content_type='text/xml'), name='squadxml'),
	url(r'^servers/$', TemplateView.as_view(template_name='servers.html'), name='servers'),

)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

galeria/models.py
from django.db import models
from sorl.thumbnail import ImageField
from audit_log.models import AuthStampedModel
from django.core.urlresolvers import reverse, reverse_lazy

# Create your models here.

class Album(AuthStampedModel):
    name = models.CharField(max_length=100, verbose_name='nazwa')
    description = models.TextField(max_length=5000, blank=True, verbose_name='opis')


    class Meta:
        verbose_name = "album"
        verbose_name_plural = "albumy"
        ordering = ['-pk']

    def __str__(self):
        return self.name



class Photo(AuthStampedModel):
    name = models.CharField(max_length=100, verbose_name='nazwa')
    file = ImageField(upload_to='photos', blank=False, null=False)
    description = models.TextField(max_length=5000, blank=True, verbose_name='opis')
    album = models.ForeignKey(Album)

    class Meta:
        verbose_name = "zdjęcie"
        verbose_name_plural = "zdjęcia"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('photo_detail', kwargs={'pk':self.pk})

    

playerprofile/views.py
from django.shortcuts import render, redirect
from permission.decorators import permission_required
from playerprofile.models import UserProfile
from django.views.generic import UpdateView, DetailView, RedirectView, ListView
from playerprofile.forms import ProfileForm
from django.core.urlresolvers import reverse_lazy, reverse

# Create your views here.

class AuthorRequiredMixin(object):
	def dispatch(self, request, *args, **kwargs):
		obj = self.get_object()
		result = super(AuthorRequiredMixin, self).dispatch(request, *args, **kwargs)
		if self.object.user != self.request.user:
			return redirect('index')
		return result


# @permission_required('playerprofile.change_userprofile', raise_exception=True)
class ProfileUpdateView(AuthorRequiredMixin, UpdateView):
	model = UserProfile
	form_class = ProfileForm
	class Meta:
		exclude = ['user']

	def get_success_url(self):
		return reverse_lazy('view_profile', kwargs={'pk':self.object.user.pk})


class ProfileView(DetailView):
	model = UserProfile

class OwnProfileView(RedirectView):
	def get_redirect_url(self, *args, **kwargs):
		return reverse_lazy('view_profile', kwargs={'pk': self.request.user.pk})



class UserList(ListView):
	queryset = UserProfile.objects.all().order_by('rank', 'user__username')

class MemberList(ListView):
	queryset = UserProfile.objects.filter(rank__importance__gte=0).order_by('rank', 'user__username')

class OwnProfileUpdateView(RedirectView):
	def get_redirect_url(self, *args, **kwargs):
		return reverse_lazy('update_profile', kwargs={'pk': self.request.user.pk})

kalendarz/templates/backup_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
{% load staticfiles %}  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    {% block style %}
    {% endblock%}
    <title>{% block title %}{% endblock %}</title>

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


</head>

<body>
  <div class="basic">
    {% include "navbar.html" %}    
  </div>
    <div class='my-background'>

      <div class="container" style="margin-top: 50px; background-color: #FFF; border-radius: 5px;">


          {% block bootstrap3_content %}

            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
          {% endblock %}

      </div> <!-- /container -->
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block script %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

kalendarz/templates/backup_navbar.html
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">INTACTILIS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Strona główna</a></li>
            <li><a href="{% url 'index' %}">Kalendarz</a></li>
            <li><a href="{% url 'archive' %}">Archiwum</a></li>
            <li><a href="http://intactilis.pl">Forum</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'account_logout' %}">Wyloguj</a></li>
                  <li><a href="{% url 'account_change_password' %}">Zmień hasło</a></li>
                  {% if user has 'cal.add_event' %}
                    <li><a href="{% url 'event_add' %}">Rozpisz misje</a></li>
                  {% endif %}
                  {% if request.user.is_staff %}
                    <li class="divider"></li>
                    <li><a href="{% url 'admin:index' %}">Panel administracyjny</a></li>
                  {% endif %}
                </ul>
              </li>
            

            {% else %}
              <li><a href="{% url 'account_signup' %}">Rejestracja</a></li>
              <li><a href="{% url 'account_login' %}">Logowanie</a></li>


            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

kalendarz/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
{% load staticfiles %}  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="badn3wz">
    <link rel="icon" href="../../favicon.ico">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <title>{% block title %}{% endblock %} | Intactilis.pl</title>

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
    {% block style %}
    {% endblock%}


</head>

<body>
  <div class="basic">
    {% include "navbar.html" %}    
  </div>
    <div class='my-background'>
      <div class="container center-block" >


          {% block bootstrap3_content %}

            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
          {% endblock %}

      </div> <!-- /container -->
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block script %}{% endblock %}
  </body>
</html>

kalendarz/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
{% load staticfiles %} 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
{% block style %}
    {% endblock%}
    <title>{% block title %}Intactilis.pl{% endblock %}</title>


{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

    <!-- Custom CSS -->
    <link href="{% static 'css/carousel.css'%}" rel="stylesheet">

</head>

<body>

    {% include "navbar.html" %}

    <!-- Full Width Image Header with Logo -->
    <!-- Image backgrounds are set within the full-width-pics.css file. -->
    {% block content%}
    


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="/static/images/1.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
              <p></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="/static/images/7.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
              <p></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="/static/images/4.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
              <p></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <h2>{{ carousel_album.photo_set.all }}</h2>
{% for photo in carousel_album.photo_set.all %}
<p>{{ photo }}</p>
{% endfor %}

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
          <a href="{% url 'album_list' %}" class="kolor">
        <div class="col-lg-4">
            <i class="fa fa-picture-o fa-5x"></i>
            <h2>Galeria</h2>
        </div><!-- /.col-lg-4 -->
          </a>
          <a href="{% url 'youtube' %}" class="kolor">
        <div class="col-lg-4">
            <i class="fa fa-youtube-square fa-5x"></i>
            <h2>Youtube</h2>
        </div><!-- /.col-lg-4 -->
          </a>
          <a href="{% url 'index' %}" class="kolor">
        <div class="col-lg-4">
            <i class="fa fa-calendar-o fa-5x"></i>
            <h2>Kalendarz</h2>
        </div><!-- /.col-lg-4 -->
          </a>
      </div><!-- /.row -->


      <hr class="featurette-divider">



      <!-- START THE FEATURETTES -->


      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading text-muted kolor">Witaj na oficjalnej stronie grupy Intactilis! </h2>
          <p class="lead kolor">Założeniem naszej grupy jest symulowanie realistycznych rozgrywek typu "COOP", 
oraz organizacja profesjonalnych szkoleń wojskowych, na których się one opierają.
W naszych szeregach znajdują się nie tylko amatorzy militarii, ale równierz osoby z doświadczeniem, 
oraz szeroką wiedzą na temat wojskowości. 
Przede wszystkim jesteśmy zgraną paczką ludzi, znających się od dawna, których połączyła wspólna pasja.
Sukcesywnie realizujemy cele, które wyznaczyliśmy sobie na początku budowania naszej grupy.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="/static/images/home501.jpg" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading text-muted kolor" style="margin-top: 10px;">Dołącz do najlepszych!</span></h2>
          <p class="lead kolor">Jeżeli podzielasz naszą pasję i jesteś zainteresowany przyłączeniem się do nas, złóż podanie juz dziś!
Znajdziesz u nas wszystko czego potrzebujesz, gwarantujemy dobrą zabawę w przyjaznym gronie,
a przedewszystkim wiedzę, która może Ci się przydać w przyszłości.</p>

        </div>
        <div class="col-md-5 col-md-pull-7">
          <div class="embed-responsive embed-responsive-16by9 center-block">
        <iframe src="https://www.youtube.com/embed/0fnhgb-aEG8" frameborder="0" scrolling="no" allowfullscreen></iframe>
      </div>
        </div>
      </div>
      </div>

      

      <!-- /END THE FEATURETTES -->


<div id="facebook_slider_widget" style="display: none"><script type="text/javascript" src="http://webfrik.pl/widget/facebook_slider.html?fb_url=https://www.facebook.com/pages/Intactilis-ArmA-3/372018453001011&amp;fb_width=290&amp;fb_height=590&amp;fb_faces=true&amp;fb_stream=true&amp;fb_header=true&amp;fb_border=true&amp;fb_theme=light&amp;chx=787&amp;speed=FAST&amp;fb_pic=sign&amp;position=LEFT"></script></div>


    {% endblock %}
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p></p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </footer>
{% block script %}{% endblock %} 

</body>

</html>

kalendarz/templates/home_base.html
<!DOCTYPE html>
<html lang="en">

<head>
{% load staticfiles %} 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
{% block style %}
    {% endblock%}
    <title>{% block title %}{% endblock %}</title>


<!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/full-width-pics.css'%}" rel="stylesheet">

</head>

<body>

    {% include "navbar.html" %}

    <!-- Full Width Image Header with Logo -->
    <!-- Image backgrounds are set within the full-width-pics.css file. -->
    {% block content%}
    <header class="image-bg-fluid-height">
        <img class="img-responsive img-center" src="http://placehold.it/200x200&text=Logo" alt="">
    </header>

    <!-- Content Section -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="section-heading">Section Heading</h1>
                    <p class="lead section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, suscipit, rerum quos facilis repellat architecto commodi officia atque nemo facere eum non illo voluptatem quae delectus odit vel itaque amet.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Fixed Height Image Aside -->
    <!-- Image backgrounds are set within the full-width-pics.css file. -->
    <aside class="image-bg-fixed-height"></aside>

    <!-- Content Section -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="section-heading">Section Heading</h1>
                    <p class="lead section-lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, suscipit, rerum quos facilis repellat architecto commodi officia atque nemo facere eum non illo voluptatem quae delectus odit vel itaque amet.</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>
    <section>
      <div class="container">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
    </section>
    {% endblock %}
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </footer>
{% block script %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

</body>

</html>

kalendarz/templates/int_tv.html
{% extends "base.html" %}
{% block title %}Streamy{% endblock %}

{% block content %}


<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#riten" aria-controls="riten" role="tab" data-toggle="tab">riten</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="riten">
    	<div class="embed-responsive embed-responsive-16by9">
			<iframe src="http://www.twitch.tv/ritenshow/embed" frameborder="0" scrolling="no" ></iframe><a href="http://www.twitch.tv/ritenshow?tt_medium=live_embed&tt_content=text_link" style="padding:2px 0px 4px; display:block; font-weight:normal; font-size:10px;text-decoration:underline;">Watch live video from RiteNshow on www.twitch.tv</a></div>

    </div>
  </div>

</div>
{% endblock %}

kalendarz/templates/int_yt.html
{% extends "base.html" %}
{% block title %}Kanały Youtube{% endblock %}

{% block content %}


<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#chiggy" aria-controls="chiggy" role="tab" data-toggle="tab">Chiggy</a></li>
    <li role="presentation"><a href="#uli" aria-controls="uli" role="tab" data-toggle="tab">Uli</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <!-- CHIGGY -->
    <div role="tabpanel" class="tab-pane fade in active" id="chiggy">
    	<div class="embed-responsive embed-responsive-16by9">
  			<iframe src="https://www.youtube.com/embed/videoseries?list=PLC7JQhVr8b8xASkO5oWkN9icD-oZS3SWv" frameborder="0" scrolling="no" allowfullscreen></iframe>
      </div>
    </div>

    <!-- ULI -->
    <div role="tabpanel" class="tab-pane fade" id="uli">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe src="https://www.youtube.com/embed/videoseries?list=PLp9kUIgGieDHKbN90-K__9_nLp5rZSpot" frameborder="0" scrolling="no" allowfullscreen></iframe>
      </div>
    </div>


  </div>

</div>
{% endblock %}

kalendarz/templates/navbar.html
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{% url 'home' %}" class="navbar-brand">INTACTILIS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}">Kalendarz</a></li>
            <li><a href="{% url 'archive' %}">Archiwum</a></li>
            <li><a href="{% url 'member_list' %}">Gracze</a></li>
            <li><a href="{% url 'servers' %}">Serwery</a></li>
            <li><a href="http://forum.intactilis.pl">Forum</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> 
                      <i class='fa fa-user'></i>
                        {{ request.user.username }} 
                    <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'account_logout' %}">
                      <i class='fa fa-sign-out'></i>
                       Wyloguj
                    </a></li>
                  <li><a href="{% url 'account_change_password' %}">
                      <i class="fa fa-key"></i>
                        Zmień hasło
                    </a></li>
                  <li><a href="{% url 'view_own_profile' %}">
                      <i class='fa fa-bars'></i>
                        Wyświetl profil</a></li>
                  <li><a href="{% url 'update_own_profile' %}">
                      <i class='fa fa-cog'></i>
                        Edytuj profil</a></li>
                  <li>
                    <a href="/media/squadxml/squad.xml">
                    <i class='fa fa-file-text'></i>
                    SquadXML</a>
                  </li>
                  {% if user has 'cal.add_event' %}
                    <li><a href="{% url 'event_add' %}">
                    <i class='fa fa-plus-square'></i>
                        Rozpisz misje</a></li>
                  {% endif %}
                  {% if request.user.is_staff %}
                    <li class="divider"></li>
                    <li><a href="{% url 'user_list' %}">
                      <i class='fa fa-users'></i>
                        Użytkownicy</a></li>
                    <li><a href="{% url 'admin:index' %}">
                      <i class='fa fa-lock'></i>
                        Panel administracyjny</a></li>
                  {% endif %}
                </ul>
              </li>
            

            {% else %}
              <li><a href="{% url 'account_signup' %}">
                <i class='fa fa-user-plus'></i>
                  Rejestracja</a></li>
              <li><a href="{% url 'account_login' %}">
                <i class='fa fa-sign-in'></i>
                  Logowanie</a></li>


            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

kalendarz/templates/servers.html
{% extends "base.html" %}
{% block title %}Streamy{% endblock %}
{% load cal_tags %}
{% block content %}
<h3>Nasze serwery:</h3>
  <!-- TEAMSPEAK -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        Teamspeak
      </h4>
    </div>
    <div class="panel-body">
      <p>Adres: intactilis.net-speak.pl</p>
      <a href="http://www.gametracker.com/server_info/178.217.190.41:6320/" target="_blank"><img src="http://cache.www.gametracker.com/server_info/178.217.190.41:6320/b_560_95_1.png" border="0" width="560" height="95" alt=""/></a>
    </div>
  </div>

  <!-- ARMA -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        Arma 3
      </h4>
    </div>
    <div class="panel-body">
      <p>Adres: intactilis.pl<br/>
      Port: 2302<br/>
        {% if request.user|in_group:"Member" %}
          <button type="button" class="btn btn-xs btn-info" data-toggle="popover" title="Hasło na serwer:" data-content="nip">Pokaż hasło</button>
        {% endif %}
      </p>
      <a href="http://www.gametracker.com/server_info/78.47.75.214:2302/" target="_blank"><img src="http://cache.www.gametracker.com/server_info/78.47.75.214:2302/b_560_95_1.png" border="0" width="560" height="95" alt=""/></a>
    </div>
  </div>




<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>
{% endblock %}